### ISSUE TITLE
webots 2023b error: Skipped unknown 'scale' field in Solid node.

### ISSUE THREAD

**Issue by antbono** [Bembelbots/WebotsLoLaController#3]
hello everyone!

I have just tried the package with the Webots2023b and i got this error on the console

`error: Skipped unknown 'scale' field in Solid node. `

This error blocks the invocation of the nao_lola_python controller. With @ijnek, we tried to  comment line 19 of SPL_Ball.proto

`scale %{=s}% %{=s}% %{=s}%`

and it works. The ball doens't even change size (strange).  Should we consider a PR?

Thanks

**Comment by sigurg** [comment]
Hi Antonio,

sorry, I fixed that issues in our code base, but forgot to push the fixes to this repo as well :/
Anyway, should be fixed now...

**Comment by antbono** [comment]
Thank you very much for the quick reply!

I have just tested it and it works fine, also the ball has the right size now.

Thanks!
